### PR TITLE
Add CoRE::CoAP::Options.register

### PR DESCRIPTION
**Pull request by cabo**
Add an interface to register per-application options and their codecs.

### CODE REVIEW

**Comment by nning** [comment]
Thanks for your contribution!

The tests fail and I postponed looking at the why until now. I could not reproduce one test failing locally so I presume, it is not worth analyzing that now. The other test fails, because a observable resource for testing at `vs0.inf.ethz.ch` is missing. Do you know of another public server with an observable resource that can be used to quickly fix this test?

**Comment by cabo** [comment]
coap.me should work, as should californium.eclipse.org (but that seems down right now).  leshan.eclipse.org seems to work:

```
http://coap.me/crawl/coap://leshan.eclipse.org
```

**Comment by cabo** [comment]
(Oops, coap.me doesn't do observable, and I don't know about leshan.)

**Comment by cabo** [comment]
http://coap.me/observe=0/coap://test.libcoap.net/time

**Comment by nning** [comment]
Thanks!

**Pull request merged**
